# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chembl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('act_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('mol_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('structure', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('torsionbv', django_rdkit.models.fields.BfpField(null=True)),
                ('atompairbv', django_rdkit.models.fields.BfpField(null=True)),
                ('mfp2', django_rdkit.models.fields.BfpField(null=True)),
                ('ffp2', django_rdkit.models.fields.BfpField(null=True)),
                ('molregno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chembl_molecule', to='chembl.MoleculeDictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Scaffold',
            fields=[
                ('scaffold_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('structure', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('smiles', models.CharField(blank=True, max_length=4000, null=True)),
                ('torsionbv', django_rdkit.models.fields.BfpField(null=True)),
                ('atompairbv', django_rdkit.models.fields.BfpField(null=True)),
                ('mfp2', django_rdkit.models.fields.BfpField(null=True)),
                ('ffp2', django_rdkit.models.fields.BfpField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScaffoldActivities',
            fields=[
                ('act_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('scaffold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Scaffold')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chembl_target', to='chembl.TargetDictionary')),
            ],
        ),
        migrations.CreateModel(
            name='TargetInteraction',
            fields=[
                ('ti_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('first_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Target')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Molecule')),
                ('second_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Target')),
            ],
        ),
        migrations.CreateModel(
            name='TargetScaffoldInteraction',
            fields=[
                ('ti_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('first_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_first', to='phin.Target')),
                ('scaffold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Scaffold')),
                ('second_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_second', to='phin.Target')),
            ],
        ),
        migrations.AddField(
            model_name='scaffoldactivities',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Target'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='scaffold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phin.Scaffold'),
        ),
        migrations.AddField(
            model_name='activities',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Molecule'),
        ),
        migrations.AddField(
            model_name='activities',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Target'),
        ),
    ]
