# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-18 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chembl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('act_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KEGGDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegg_id', models.CharField(max_length=64, unique=True)),
                ('all_gene_accessions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None)),
                ('chembl_mappings', models.ManyToManyField(to='chembl.ComponentSequences')),
            ],
        ),
        migrations.CreateModel(
            name='KEGGDiseaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegg_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='phin.KEGGDiseaseClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RHAct', models.FloatField()),
                ('LHAct', models.FloatField()),
                ('transform', models.CharField(max_length=2048)),
                ('core', models.CharField(max_length=2048)),
                ('LHAssay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_hand_assay', to='chembl.Assays')),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('mol_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('structure', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('torsionbv', django_rdkit.models.fields.BfpField(null=True)),
                ('atompairbv', django_rdkit.models.fields.BfpField(null=True)),
                ('mfp2', django_rdkit.models.fields.BfpField(db_index=True, null=True)),
                ('ffp2', django_rdkit.models.fields.BfpField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoleculeHierarchy',
            fields=[
                ('molregno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phin_hierarchy', serialize=False, to='chembl.MoleculeDictionary')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chembl.MoleculeDictionary')),
            ],
        ),
        migrations.CreateModel(
            name='MoleculeInteraction',
            fields=[
                ('moli_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('target', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('min', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('max', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('mean', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('median', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('first_molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Molecule')),
                ('second_molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Molecule')),
            ],
        ),
        migrations.CreateModel(
            name='Scaffold',
            fields=[
                ('scaffold_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('structure', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('smiles', models.CharField(blank=True, max_length=4000, null=True)),
                ('torsionbv', django_rdkit.models.fields.BfpField(null=True)),
                ('atompairbv', django_rdkit.models.fields.BfpField(null=True)),
                ('mfp2', django_rdkit.models.fields.BfpField(db_index=True, null=True)),
                ('ffp2', django_rdkit.models.fields.BfpField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScaffoldActivities',
            fields=[
                ('act_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('scaffold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Scaffold')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phin_target', to='chembl.TargetDictionary')),
            ],
        ),
        migrations.CreateModel(
            name='TargetNetwork',
            fields=[
                ('ti_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('molecule', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, size=None)),
                ('min', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('max', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('mean', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('median', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('first_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Target')),
                ('second_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Target')),
            ],
        ),
        migrations.CreateModel(
            name='TargetScaffoldNetwork',
            fields=[
                ('ti_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('scaffold', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, size=None)),
                ('min', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('max', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('mean', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('median', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('first_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_first', to='phin.Target')),
                ('second_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_second', to='phin.Target')),
            ],
        ),
        migrations.AddField(
            model_name='scaffoldactivities',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Target'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='molregno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phin_molecule', to='chembl.MoleculeDictionary'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='scaffold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phin.Scaffold'),
        ),
        migrations.AddField(
            model_name='mmp',
            name='LHMol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_hand_mol', to='chembl.MoleculeDictionary'),
        ),
        migrations.AddField(
            model_name='mmp',
            name='RHAssay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_hand_assay', to='chembl.Assays'),
        ),
        migrations.AddField(
            model_name='mmp',
            name='RHMol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_hand_mol', to='chembl.MoleculeDictionary'),
        ),
        migrations.AddField(
            model_name='mmp',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chembl.TargetDictionary'),
        ),
        migrations.AddField(
            model_name='keggdisease',
            name='kegg_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phin.KEGGDiseaseClass'),
        ),
        migrations.AddField(
            model_name='activities',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Molecule'),
        ),
        migrations.AddField(
            model_name='activities',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Target'),
        ),
    ]
