# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chembl', '0001_initial'),
        ('phin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('level', models.IntegerField()),
                ('chembl_mappings', models.ManyToManyField(to='chembl.TargetDictionary')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='phin.ICD')),
            ],
        ),
        migrations.AlterField(
            model_name='molecule',
            name='mfp2',
            field=django_rdkit.models.fields.BfpField(null=True),
        ),
    ]
