# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembl', '0001_initial'),
        ('phin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RHAct', models.FloatField()),
                ('LHAct', models.FloatField()),
                ('transform', models.CharField(max_length=2048)),
                ('LHAssay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_hand_assay', to='chembl.Assays')),
                ('LHMol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_hand_mol', to='phin.Molecule')),
                ('RHAssay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_hand_assay', to='chembl.Assays')),
                ('RHMol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_hand_mol', to='phin.Molecule')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Target')),
            ],
        ),
    ]
