# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0002_mmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmp',
            name='core',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
