# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0002_auto_20170420_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetinteraction',
            name='ti_id',
        ),
        migrations.AddField(
            model_name='targetinteraction',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
