# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0003_mmp_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmp',
            name='LHMol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_hand_mol', to='chembl.MoleculeDictionary'),
        ),
        migrations.AlterField(
            model_name='mmp',
            name='RHMol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_hand_mol', to='chembl.MoleculeDictionary'),
        ),
        migrations.AlterField(
            model_name='mmp',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chembl.TargetDictionary'),
        ),
    ]
