# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0004_auto_20171128_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeInteraction',
            fields=[
                ('moli_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('first_molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Molecule')),
                ('second_molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Molecule')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Target')),
            ],
        ),
    ]
