# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0004_auto_20170420_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetinteraction',
            name='ti_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
