# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-17 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0004_auto_20181217_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd',
            name='icd_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
