# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0005_moleculeinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='first_molecule',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='max',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='median',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='min',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='second_molecule',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='target',
        ),
    ]
