# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 14:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0006_auto_20180104_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleculeinteraction',
            name='first_molecule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Molecule'),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='max',
            field=models.FloatField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='mean',
            field=models.FloatField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='median',
            field=models.FloatField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='min',
            field=models.FloatField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='second_molecule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Molecule'),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='target',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
