# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0007_auto_20180104_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='max',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='median',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='min',
        ),
        migrations.AlterField(
            model_name='moleculeinteraction',
            name='first_molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Molecule'),
        ),
        migrations.AlterField(
            model_name='moleculeinteraction',
            name='second_molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Molecule'),
        ),
    ]
