# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0008_auto_20170420_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetinteraction',
            name='first_target',
        ),
        migrations.RemoveField(
            model_name='targetinteraction',
            name='molecule',
        ),
        migrations.RemoveField(
            model_name='targetinteraction',
            name='second_target',
        ),
    ]
