# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 14:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0008_auto_20180104_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleculeinteraction',
            name='max',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='mean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='median',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='min',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
