# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0009_auto_20180104_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='first_molecule',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='max',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='median',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='min',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='moli_id',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='second_molecule',
        ),
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='target',
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
