# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 06:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0010_auto_20180105_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moleculeinteraction',
            name='id',
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='first_molecule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Molecule'),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='max',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='mean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='median',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='min',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='moli_id',
            field=models.BigAutoField(db_index=True, default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='second_molecule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Molecule'),
        ),
        migrations.AddField(
            model_name='moleculeinteraction',
            name='target',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
