# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0010_auto_20170420_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaffoldActivities',
            fields=[
                ('act_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('scaffold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Scaffold')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Target')),
            ],
        ),
    ]
