# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0011_auto_20180105_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moleculeinteraction',
            name='first_molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Molecule'),
        ),
        migrations.AlterField(
            model_name='moleculeinteraction',
            name='second_molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Molecule'),
        ),
    ]
