# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0011_scaffoldactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetScaffoldInteraction',
            fields=[
                ('ti_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('first_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_first', to='phin.Target')),
                ('scaffold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phin.Scaffold')),
                ('second_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_second', to='phin.Target')),
            ],
        ),
    ]
