# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0015_keggdisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keggdisease',
            name='kegg_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phin.KEGGDiseaseClass'),
        ),
        migrations.AlterField(
            model_name='keggdisease',
            name='kegg_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
