# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 01:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0016_auto_20180111_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetNetwork',
            fields=[
                ('ti_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('molecule', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, db_index=True, size=None)),
                ('min', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('max', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('mean', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('median', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('first_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first', to='phin.Target')),
                ('second_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second', to='phin.Target')),
            ],
        ),
        migrations.CreateModel(
            name='TargetScaffoldNetwork',
            fields=[
                ('ti_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('molecule', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, db_index=True, size=None)),
                ('min', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('max', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('mean', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('median', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('first_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_first', to='phin.Target')),
                ('second_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_scaffold_second', to='phin.Target')),
            ],
        ),
        migrations.AlterField(
            model_name='targetinteraction',
            name='first_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ti_first', to='phin.Target'),
        ),
        migrations.AlterField(
            model_name='targetinteraction',
            name='second_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ti_second', to='phin.Target'),
        ),
        migrations.AlterField(
            model_name='targetscaffoldinteraction',
            name='first_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ti_scaffold_first', to='phin.Target'),
        ),
        migrations.AlterField(
            model_name='targetscaffoldinteraction',
            name='second_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ti_scaffold_second', to='phin.Target'),
        ),
    ]
