# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 02:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0018_auto_20180115_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetscaffoldnetwork',
            name='molecule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, size=None),
        ),
    ]
