# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0019_auto_20180115_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetscaffoldnetwork',
            old_name='molecule',
            new_name='scaffold',
        ),
    ]
