# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phin', '0021_auto_20180120_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetinteraction',
            name='first_target',
        ),
        migrations.RemoveField(
            model_name='targetinteraction',
            name='molecule',
        ),
        migrations.RemoveField(
            model_name='targetinteraction',
            name='second_target',
        ),
        migrations.RemoveField(
            model_name='targetscaffoldinteraction',
            name='first_target',
        ),
        migrations.RemoveField(
            model_name='targetscaffoldinteraction',
            name='scaffold',
        ),
        migrations.RemoveField(
            model_name='targetscaffoldinteraction',
            name='second_target',
        ),
        migrations.DeleteModel(
            name='TargetInteraction',
        ),
        migrations.DeleteModel(
            name='TargetScaffoldInteraction',
        ),
    ]
